version: '3.1'
services:
  database:
    container_name: api_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : JavaQuest
      POSTGRES_PASSWORD: JavaQuest
      POSTGRES_DB: JavaQuest
    ports:
      - "5432:5432"
