INSERT INTO hero (name, image, level, health_point, attack_point, defense_point, magic_point, exp, speed)
VALUES ('Hero1', NULL, 1, 8, 5, 2, 2, 0, 1);

INSERT INTO monsters (name, image, hp_min, hp_max, atk_min, atk_max, def_min, def_max, mag_min, mag_max, xp_drop,
                      speed_min, speed_max)
VALUES ('Gobelin', 'gobelin.png', 6, 8, 2, 3, 1, 3, 1, 2, 101, 2, 5),
       ('Chef des gobelin', 'goblin_king.png', 20, 22, 3, 5, 2, 4, 2, 3, 101, 1, 3),
       ('Aventurier', 'Aventurier.png', 8, 12, 2, 4, 3, 5, 1, 2, 101, 1, 8),
       ('Gladiateur', 'gladiateur.png', 8, 12, 3, 6, 2, 5, 1, 2, 101, 1, 8),
       ('groupe d''aventurier', 'aventurier_group.png', 40, 60, 12, 22, 7, 10, 1, 2, 450, 1, 8),
       ('L''effaceur de personnage', 'cheese.png', 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99);

INSERT INTO story (descriptionID, text_description, localisation, image, option1, redirection1, option2, redirection2,
                   option3, redirection3, option4, redirection4, effects, monsterID)
VALUES (1,
        'Bonjour, et bienvenue dans Javaquest. Vous vous appretez à vivre une aventure incroyable, où vos décisions seront importantes, et vos ennemis implacables. ' ||
        'Voyons un peu comment vous souhaitez jouez votre héros. Face à un adversaire, comment décidez vous de combattre ? ',
        '???', 'debut.jpg', 'Prudemment. Je dois attendre le moment opportun pour frapper (+ 2 pv)', 2,
        'Taper. Fort. ( +1 attaque)', 3,
        'J utiliserais ma puissante armure pour échanger les attaques avec mon adversaire. Mais en ayant toujours un avantage ( +1 défense)',
        4,
        'Rapide, efficace, frappant avant que mon adversaire ne puisse réagir (+2 vitesse)', 5, NULL, NULL),
       (2,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', 'debut.jpg', 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'health_point:2', NULL),
       (3,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', 'debut.jpg', 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'attack_point:1', NULL),
       (4,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', 'debut.jpg', 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'defense_point:1', NULL),
       (5,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', 'debut.jpg', 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'speed :2', NULL),
       (6,
        'Espérons que tes pulsions de violences te permettront tout de même de survivre. Es tu prêt à partir en aventure ?',
        '???', 'debut.jpg', 'Je suppose ?', 8, 'ABSOLUMENT !', 8, 'Pas vraiment le choix en fait...', 8,
        'Euh.... non ?', 8,
        NULL, NULL),
       (7, 'Un bel état d esprit ! Es tu prêt à partir en aventure ?', '???', 'debut.jpg', 'Je suppose ?', 8,
        'ABSOLUMENT !',
        8, 'Pas vraiment le choix en fait...', 8, 'Euh.... non ?', 8, NULL, NULL),
       (8,
        'Vous êtes, un aventurier de la guilde de Tantrop. Que ce soit à la recherche de gloire, de fortune, d''aventure ou de quelques relations hauts placés, vous avez réussis le difficile test de recrutement et êtes désormais un stagiaire aventurier, à la recherche d''un Contrat de Decouverte et d''Initiation, premier pas dans le vrai monde d''un aventurier. Assis au milieu de la taverne, vous attendez l''arrivé dIsabella, responsable de la guilde, qui va vous proposer une quete à réaliser... ' ||
        'Une naine aux cheveux roux, de longues couettes attaché par 2 gros anneaux de métal, les cheveux bouclés se présente devant vous. Son visage rond décorés d yeux semblables à 2 émeraudes et des lèvres fines, vous sourit tendrement,avant de transformer son visage en une grimace de dégout et vulgaire.' ||
        '"Bon sang, on accepte vraiment n''importe qui ici de nos jours. T''es censé être quoi en fait ?',
        'Taverne de Tantrop', 'tavern.png', 'Isabella, je suppose ?', 9,
        'Je te permet pas de me parler comme ça. Tu cherches les problèmes ?', 10,
        'Un stagiaire aventurier ne souhaitant que faire ses preuves !', 11,
        'Je ne sais pas vraiment...Mon école m''impose un stage et j''ai juste été pris(e) ici...', 11, NULL, NULL),
       (9,
        '"Elle même. Cheffe en second de la guilde. Tu dois être le nouveau stagiaire ici je suppose ? Je vais te filer une petite quête, facile et rapide. Enfin, si t es pas trop stupide. Heh... ',
        'Taverne de Tantrop', 'tavern.png', 'Stupide moi ? Je suis peut-être idiot mais pas non plus stupide hein..',
        11,
        'Je suis stagiaire ici oui. Merci de m offrir une chance', 11,
        'Tu oses m insulter ? Je vais t apprendre le respect moi... *Frapper Isabella*', 10,
        'Jai hate de chatier mes ennemis...', 11, NULL, NULL),
       (10,
        'Avant d avoir put réagir, une baffe capable de déboiter une machoire se pose "délicatement" sur votre joue. Un son lourd et sourd résonnant dans votre crane vous fait perdre la vue quelques secondes. Vous ne parvenez qu''à entendre que le son de votre sang montant par pulsion dans votre cerveau, votre corps luttant pour reprendre conscience. Votre vue revient petit à petit, et vous appercevez Isabella, tournant son poignet, le regard fier et hautain. Vous avez perdu 2 pv.' ||
        '" Tu disais le nouveau ?', 'Taverne de Tantrop', 'tavern.png', 'Pardon', 11, 'C''était...innatendu... ', 11,
        'Je rigolais, je te jure...;', 11,
        'Tu verras quand je serais plus fort. J''aurais ma revanche...', 11, 'health_point : -2', NULL),
       (11,
        '" Formidable ! Voici ta quête : Un groupe de gobelin au nord de la ville ont commencé à piller les caravanes marchandes et les villages alentours. Cependant, ils ne semblent pas être particulièrement violent. Ils pillent, blessent parfois, mais n''ont tué que ceux qui l''ont attaqué. Un stratagème inhabituel pour des gobelins. Va sur place, comprend ce qu''il se passe, et règle le problème. Des questions ? *Son poing se lève*  ',
        'Taverne de Tantrop', 'tavern.png', 'Non...', 12, 'Non...', 12, 'Non...', 12,
        'En fait, oui...', 12, NULL, NULL),
       (12,
        '"Très bien ! Bon courage alors" Isabella tourne les talons, vous laissant seul à votre table. Que souhaitez vous faire ?',
        'Taverne de Tantrop', 'tavern.png', 'Eh bah direction le nord alors...', 13,
        'Il me faudrait de l''argent. Et de l''équipement. Direction le marché avant tout ', 14,
        'Il me faudrait de l argent, et vite. Direction l''arène !', 15,
        'Personne ne m''en voudra si.... "j''emprunte" un peu d''équipement à la guilde n''est ce pas ? Direction les casiers privés des autres aventuriers...',
        16, NULL, NULL),
       (13,
        ' Une odeur fétide agresse vos narines alors que vous arrivez aux écuries du nord de la ville. Devant vous, des chevaux sellés attachés semblent attendre leur cavaliers. A coté, un groupe de marchand préparent leur cargaisons dans un chariot tiré par deux mules. Enfin, la porte permettant de sortir de la ville est grande ouverte devant vous  ',
        'Ecuries de Tantrop', 'ecurie.png', 'Ce cheval sera à moi...', 17,
        'Parlons au propriétaire. J''ai besoin d''un cheval', 18,
        'Bah ! J''irais à pied', 19,
        'Allons parler aux marchands.Isabella a bien dit que les gobelins les attaquaient non ?', 20, NULL, NULL),
       (14,
        'Les étals colorés débordent d''une myriade de marchandises exotiques venues des confins du monde connu. Les odeurs enivrantes d''épices rares et de potions magiques flottent dans l''air, tandis que le brouhaha des négociations et les rires des marchands créent une symphonie animée par des musiciens créant une ambiance envoutante. Des tentes ornées de drapés chatoyants s''étirent sous le ciel, abritant des trésors éblouissants, des artefacts mystiques, des bijoux incrustés de gemmes aux propriétés mystiques, des étoffes aux couleurs éclatantes de tissus enchantés, des herbes rares aux vertus curatives et des marchandises inconnues...Des forgerons martèlent le métal avec une habileté ancestrale, créant des armes ornées de runes magiques',
        'Le marché', 'marche.png',
        'Magnifique. Essayons d''acheter de l''équipement !', 21,
        'J''ai pas d''argent. Tant pis, voyons ce que je peux voler...', 22,
        'Je suis un as de la négociation. J''arriverais bien à choper 2-3 trucs gratos', 105,
        'Pas d''argent... J''en aurais une fois la quete accomplis, allons-y', 13,
        NULL, NULL),
       (21, 'Vous...n''avez pas d''argent...',
        'Le marché', 'marche.png',
        'C''est vrai... bon bah retour à la quête alors"', 13,
        'Tant pis...je vais voler ce que je peux', 22,
        'Ah oui... bon bah j''irais m''équiper à l''arène', 15,
        'Je suis sur que je peux négocier un peu d''équipement gratuitement', 21, NULL, NULL),
       (22,
        'Vous approchez d''un étable, et voyez une proie qui semble être facile à dérober. Une femme, penché sur un comptoir, observant des bijoux étincellant de mille couleur, sa bourse pendant à sa ceinture',
        'Le marché', 'marche.png',
        'Prendre discrètement sa bourse', 74,
        'C''est une mauvaise idée. Trop de gens. Négocier avec les marchands plutôt...', 105,
        'Laisser tomber et partir faire la quête', 13,
        'Moins de risque à faire l''arène...Y aller au lieu de se risquer à la garde', 15, NULL, NULL),
       (105,
        'Vous approchez d''un marchand. Un gnome, les yeux émeraudes, les cheveux blancs plaqué vers l''arrière, un bouc pointant vers l''avant. Habillé d''un manteau rouge et d''un pantalon noir, le gnome vous épie du regard, un sourire sournois envoyé dans votre direction. "Bonjour, et bienvenue chez Gimble. Que puis-je faire pour vous ?"',
        'Le marché', 'marche.png',
        'Bonjour Gimble. Laissez moi vous proposer un arrangement. J''ai besoin d''équipement de toute urgence mais je n''ai pas d''argent. Offrez moi quelque chose gratuitement, et je vous le rembourserais 20% plus cher',
        83,
        'Gimble, je n''ai pas d''argent, mais je suis un futur grand aventurier. Offrez moi quelque chose, je ne l''oublierais pas !',
        83,
        'Pourriez vous me preter un peu d''équipement ?', 83,
        'Donne moi tout ton argent et tout ton équipement si tu veux pas que tes intestins décorent le sol', 86, NULL,
        NULL),
       (83,
        '"Bahahah ! Non. Mais pourquoi pas ça plutot. Je te prête un objet, et quand tu me le rends, tu me donnes 80% de son prix."',
        'Le marché', 'marche.png',
        'C''est beaucoup trop cher ! Disons 20%', 84,
        'Non, je vous le rembourse juste intégralement.', 85,
        'Je préfère aller tenter ma chance à l''arène', 15,
        'Vous savez quoi ? Laissez tomber. Donnez moi tout ce que vous avez immédiatement', 86, NULL, NULL),
       (84, '"70%"',
        'Le marché', 'marche.png',
        '35%', 85,
        '20%', 104,
        '60% ?', 87,
        'Pff. Non. Donner tout, gratuitement, maintenant, ou je vous éventre', 86, NULL, NULL),
       (104, 'Vous pouvez prendre la porte messire !',
        'Le marché', 'marche.png',
        'Aller vous faire...', 13,
        'j''ai aps besoin de vous...', 13,
        'Merci Gimble. Quand je serais mort par votre faute je penserais à vous', 13,
        ' D''accord d''accord 50% s''il vous plait !!!', 87, NULL, NULL),
       (86,
        'Vous n''avez pas le temps de réagir que d''un claquement de doigt du gnome, vous vous retrouvez menotté devant la porte de la prison. "Tient ? Encore un qui a tenté de voler Gimble !" Vous vous retrouvez en prison, vos espoirs de CDI anéantis...',
        'GAME OVER', 'prison.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (85, '"Je refuse. 50%, c''est mon dernier prix. Et votre prochain achat d''équipement devra être chez moi"',
        'Le marché', 'marche.png',
        'Non c''est trop. Aller voir ailleur pour arnaquer les gens, j''ai une quête à accomplir', 13,
        '40% ? S''il vous plait...', 87,
        'Et puis quoi encore ? Je préfère tenter ma chance à l''arène...', 15,
        'Non. Donnez moi l''intégralité de votre stock. TOUT DE SUITE', 86,
        NULL, NULL),
       (87, 'Le gnome soupir et baisse les yeux. "Bon aller c''est d''accord. Prenez un objet et revenez victorieux',
        'Le marché', 'marche.png',
        'Je vais prendre l''épée ! (+2 attaque)', 88,
        'Je vais prendre l''armure ! (+2 défense)', 89,
        'Je vais prendre des potions ! (+4 pv)', 102,
        'Je vais prendre les bottes ! (+2 vitesse)', 103, NULL, NULL),
       (88, 'Vous prenez l''épée, et un sentiment de puissance vous emplie',
        'Le marché', 'marche.png',
        'Direction le nord', 13,
        'il est temps d''accomplir enfin cette quête !', 13,
        'Merci Gimble. Je ne l''oublierais pas', 13,
        'Allez salut !', 13, NULL, NULL),
       (89, 'Vous prenez l''armure, et un sentiment de confort vous emplie',
        'Le marché', 'marche.png',
        'Direction le nord', 13,
        'il est temps d''accomplir enfin cette quête !', 13,
        'Merci Gimble. Je ne l''oublierais pas', 13,
        'Allez salut !', 13, NULL, NULL),
       (102, 'Vous prenez les potions et les buvez, Vous vous sentez plus résistant',
        'Le marché', 'marche.png',
        'Direction le nord', 13,
        'il est temps d''accomplir enfin cette quête !', 13,
        'Merci Gimble. Je ne l''oublierais pas', 13,
        'Allez salut !', 13, NULL, NULL),
       (103, 'Vous prenez les bottes, et un sentiment de légerté vous emplie',
        'Le marché', 'marche.png',
        'Direction le nord', 13,
        'il est temps d''accomplir enfin cette quête !', 13,
        'Merci Gimble. Je ne l''oublierais pas', 13,
        'Allez salut !', 13, NULL, NULL),
       (15,
        'Les bruits d''armes d''acier se fracassant les unes contre les autres resonnent dans l''accueil de l''arène. Les cris de guerres, de douleur, et de victoire semblable à des échos terrifiant dans la salle. Un homme s''approche de vous, grand, musclé, les bras croisés. "Salut. Tu veux quoi ici ? "',
        'Arène de Tantrop', 'arena.jpg',
        'Euh... rien je me suis perdu...Je voulais aller au nord', 13,
        'GLOIRE ET FORTUNE', 81,
        'Rien je cherchais les toilettes du marché. Je vais y retourner...', 14,
        'Vous parlez à un (stagiaire) aventurier, un peu de respect ! Je viens m''échauffer avant de partir en quête !',
        81,
        NULL, NULL),
       (81,
        '"Ca c''est l''esprit ! T''es sur d''en avoir assez dans le ventre par contre ? La mort arrive vite dans l''arène. Même si les récompenses valent le coup ! "',
        'Arène de Tantrop', 'arena.jpg',
        'J''ai changé d''avis... je vais faire ma quête plutôt...', 13,
        'Ca va être facile. Donne moi ce que tu as de mieux !', -82,
        'Je suppose. Je suis meilleur qu''il n''y parrait...', -82,
        'Ah on peut mourir ? Finalement non, j''ai pas envie de recommencer du début...Je vais aller au Nord', 13, NULL,
        4),
       (82,
        'Jolie victoire camarade ! Tu gagnes l''armure et l''arme de ton ancien adversaire, en plus d''être maintenant un adversaire chevronné',
        'Arène de Tantrop', 'arena.jpg',
        'Trop facile ! Je vais plier ma quête maintenant', 13,
        'Merci pour l''echauffement. Direction le Nord !', 13,
        'Pff trop dur. Je vais eviter de me battre à l''avenir...', 13,
        'Dite...je peux me rebattre ? ', -82, 'attack_point : 1 ; defense_point : 1', 4),
       (16,
        'Vous entrez au niveau des dortoirs de la guilde, une succession de lit superposé dans une grande salle, avec un coffre au pied de chacun d''entre eux. Certains aventuriers dorment encore...',
        'Dortoir de la guilde', 'dortoir.jpg',
        '*S''approcher du coffre d''un lit où personne ne dort...*', 23,
        '*S''approcher du coffre d''un lit où un aventurier dort...*', 34,
        '*Reveiller un aventurier pour lui demander de l''aide ', 35,
        '*Réflechir à une distraction pour faire sortir les gens de la salle*', 39, NULL, NULL),
       (17,
        'Vous sautez sur le cheval, coupez la corde, et le fait partir au galot, au milieu et à la vue de tout le monde. La surprise de l''action fait que les gardes n''ont pas le temps de réagir que vous êtes déjà loin, en direction pour votre quête',
        'Ecuries de Tantrop', 'ecurie.png',
        'Rire machiaveliquement', 46,
        'Hurler de joie, votre crime fut si facile', 46,
        'Regretter votre décision et rendre le cheval', 99,
        'Accelerer, vous accomplirez votre quêtes et vous justifierez plus tard.', 46, NULL, NULL),
       (46,
        'Vous arrivez à destination en quelques heures. Sur un chemin pavé, entouré d''arbres sombres, l''odeur des pins vous caressant les narines, vous appercevez des petites ombres de la taille d''un enfant s''approcher de vous, équipez de couvercle de poubelles, de marmittes, de louche de couteau et de baton pointus',
        'Foret sombre', 'forest.jpg',
        'Des gobelins ? A L''ATTAQUE !', -48,
        'Vous...êtes quoi ?', 47,
        'Euh...bonjour ?', 47,
        'Ne nous battons pas. Discutons. ', 47, NULL, 1),
       (18,
        'Le gérant de l''écurie se présente à vous. Un homme grand, musclé, une grade et soyeuse moustache cachant ses lèvres supérieurs. "Je peux faire quelques chose pour vous ?" ',
        'Ecuries de Tantrop', 'ecurie.png',
        'Donner moi un cheval', 73,
        'J''aimerais vous louer un cheval', 76,
        'Je dois aller vers le Nord. Pourriez vous m''y emmener ?', 73,
        'J''aimerais vous acheter un cheval', 73, NULL, NULL),
       (76, 'Ouaip, mais vous avez pas assez d''argent je pense pour ça si ?',
        'Ecuries de Tantrop', 'ecurie.png',
        'Euh si, si , j''ai gagné à l''arène, j''ai gagné là bas ils vous paieront !', 77,
        'Non...Mais en revenant de ma quete je vous paierai !', 77,
        'Non...Mais mon...père si ! Duc Louis Maltazor De Gille ! Allez le voir, il vous paiera !', 77,
        'Non, désolé...je vais plutôt demander aux marchands ', 20, NULL, NULL),
       (77, '"Mouais...bon...Ok. Mais j''ai interet à être payé..."',
        'Ecuries de Tantrop', 'ecurie.png',
        'Merci beaucoup', 46,
        'Au revoir', 46,
        'Ne rien dire', 46,
        'Pfff, bouffons...', 46, NULL, NULL),
       (73,
        '"S''il vous plait. Et je doute que vous ayez les moyens avec votre salaire de stagiaire. Aller plutôt demander aux marchands de vous emmenez." Il se retourne pour indiquer les marchands non loin d''ici',
        'Ecuries de Tantrop', 'ecurie.png',
        'Vous profitez de cette instant d''inatention pour sauter sur le cheval et partir avec', 17,
        'Vous laissez tomber, vous irez à pieds...', 19,
        'Tentez de voler la bourse du vendeur', 74,
        'Aller voir les marchands', 12, NULL, NULL),
       (74,
        'Vous tentez de voler la bourse, au milieu de tout le monde. A peine la main posé dessus, qu''un garde vous attrape le poignet. "Vous m''expliquez ?"',
        '', 'marche.png',
        'Il y avait un moustique dessus, je vous jure...', 75,
        'Vous ne m''arreterez pas', 75,
        'Je prenais la bourse qui me revient de droit. C''est lui qui me l''a volé au départ !', 75,
        'Partir en courant à pied vers le Nord. Vous expliquerez tout une fois votre quête accomplis', 19, NULL, NULL),
       (75, '"Je crois pas non". Le garde vous arrete, et vous dites adieu à votre stage et votre CDI. Game Over',
        'Game Over', 'prison.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (19,
        'Vous partez à pied. Le voyage est long, et vos pieds souffriront du voyage, ce qui vous blesse et vous ralentiera ( -1 pv et -1 vitesse)',
        'Forêt Sombre', 'forest.jpg',
        'Continuer...', 46,
        'Continuer...', 46,
        'Continuer...', 46,
        'Continuer...', 46, 'health_point:-1;speed:-1', NULL),
       (20,
        'Les marchands ne vous remarquent pas, trop occupé à charger leur cargaison dans leur chariot. Un drap posé par dessus de celui-ci cache les marchandises',
        'Ecuries de Tantrop', 'ecurie.png',
        'Se glisser discrètement dans le chariot', 78,
        'Aller parler aux marchands', 79,
        'Bruler le chariot, profiter de la distractions pour sauter sur le cheval', 17,
        'Laisser tomber et voler un cheval', 17, NULL, NULL),
       (78,
        'Vous vous glissez discrètement sous les draps du chariot. Au bout de quelques minutes, le claquement des lanières de cuirs indiquent que le chariot va partir. Celui-ci vibre sur les dalles, rendant le trajet désagréable. Après quelques heures, votre corps ne supporte plus le manque de confort du trajet. Fort heuresement, votre destination a été atteintes. Vous vous glissez discrètement en dehors de votre monture, et la regardez partir au loin.',
        'Forêt sobmre', 'ecurie.png',
        'Continuer', 46,
        'Continuer', 46,
        'Continuer', 46,
        'Continuer', 46, NULL, NULL),
       (79,
        'Les marchands vous remarquent, s''arretent quelques instants pour vous adresser la parole." Vous désirez ?"',
        'Ecuries de Tantrop', 'ecurie.png',
        'Je dois me rendre au nord. Puis-je vous accompagner ? (gratuitement si possible)', 80,
        'Je travail pour la guilde. J''ai besoin de me rendre au nord. Emmenez-y moi', 80,
        'Laisser tomber et partir à pied', 19,
        'Pousser le marchand et profiter de la distraction pour voler un cheval', 17, NULL, NULL),
       (80,
        'Les marchands se regardent une seconde à peine, avant de répondre :" Oui sans problème. Nous allons vers le nord aussi. Installez vous". Vous montez alors dans le chariot, et celui-ci partira au bout de quelques minutes. Vous atteignez en quelques heures votre destination, puis descendez de votre moyen de locomotion, avant de la regarder partir au loin',
        'Ecuries de Tantrop', 'ecurie.png',
        'Continuer', 46,
        'Continuer', 46,
        'Continuer', 46,
        'Continuer', 46, NULL, NULL),
       (23, 'Vous vous approchez d''un coffre en face d''un lit vide...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Faire demi-tour. C''était peut-être une mauvaise idée', 12,
        'Ouvrir le coffre...', 24,
        'Prendre le coffre. On l''ouvrira plus tard...', 25,
        'Inspecter le coffre', 26, NULL, NULL),
       (24, 'Le coffre s''ouvre sans opposer de résistance. Une petite dague est trouvable à l''intérieur !',
        'Dortoir de la guilde ', 'dortoir.jpg',
        'Prendre la dague ! (+1 attaque)', 27,
        'Laisser la dague. Le vol c''est mal...', 16,
        'Prendre la dague et planter les aventurier. On sera plus tranquille sans eux dans le dortoir...', 28,
        'Crier au vol et indiquer une direction pour faire partir les aventuriers', 40, NULL, NULL),
       (25, 'Vous essayer de tirer le coffre, mais celui-ci est trop lourd...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Prendre une inspiration et reessayer', 25,
        'Tant pis, ouvrir le coffre...', 24,
        'Inspecter le coffre, peut être que quelque chose bloque le coffre...', 26,
        'Laisser tomber. C''est trop dangereux de voler la guilde...', 12, NULL, NULL),
       (26,
        'Le coffre est en bois avec des gondons de métal lourd pour le soutenir. Pas de cadenas visible. Après courte inspection, il semble cloué dans le sol...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Ouvrir le coffre', 24,
        'Laissez tomber et aller ailleur...', 12,
        'Laisser tomber et demander de l''aide à un aventurier plutôt que de les voler', 0,
        'Insister. Le coffre. Cèdera.', 25, NULL, NULL),
       (27, 'Vous prenez la dague !',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Planter un aventurier pour essayer la dague', 28,
        'Planter les aventuriers pour les dépouiller de leur richesse. Après tout, morts, elles vous seront plus utiles',
        28,
        'Partir avant de vous faire reperer, et partir au Nord', 13,
        'Avec ça, aucune chance de perdre à l''Arène. Direction celle-ci !', 15,
        'attack_point : 1', NULL),
       (28,
        'Votre dague en main, vous cedez à vos pulsions de violence et plantez un aventurier. La lame s''enfonce dans sa gorge, le sang pulsant dans un rythme régulier en dehors de son corps. Les yeux de votre victime s''écarquillent de terreur, ses yeux rouges, au bord des larmes, tandis qu''il commence à convulser de douleur, un son de rale tandis qu''il s''étouffe dans son propre sang, avant d''être un cadavre inerte, encore chaud, devant vous',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Piller le coffre et le cadavre', 29,
        '......En planter un autre....', 30,
        'Partir d''ici rapidement, l''odeur va rapidement attirer du monde. Direction le Nord', 13,
        'Crier au meurtre en indiquant une direction', 41, 'attack_point : 1', NULL),
       (29,
        'Les gemissements de votre victime ont commencé à reveiller quelques personnes. Des mouvements de draps, des grognements, suivi d''un leger "Que se passe-t-il ?" resonnent dans le dortoir...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Il a une épée sur lui. La prendre et partir en courant !', 31,
        'Il a une armure sur lui. La prendre et partir en courant !', 32,
        'Des potions ! Les prendre et partir en courant !', 33,
        'PRENDRE TOUT', 30, NULL, NULL),
       (30,
        'Le bruit incessant que vous avez provoqué à reveillé les occupants du dortoir. Les aventuriers se lèvent, et observent votre crime, dégainant leurs armes et chargeant vers vous ! ',
        'Dortoir de la guilde', 'dortoir.jpg',
        'JE NE MOURRAIS PAS SANS ME BATTRE', -98,
        'Zut', 99,
        'C''EST PAS MOI JE VOUS JURE !', 99,
        'Tout ceci n''est qu''un mauvais rêve.... rendormez vous....', 99, NULL, 5),
       (31, 'Vous prenez une épée avant de fuir le dortoir',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Direction le Nord', 13,
        'Direction l''Arène !', 15,
        'Direction le marché', 14,
        '...Retourner au dortoir. Vous avez peut être oublié quelque chose', 30, 'attack_point : 1', NULL),
       (32, 'Vous prenez une armure avant de fuir le dortoir',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Direction le Nord !', 13,
        'Direction l''Arène !', 15,
        'Direction le marché !', 14,
        '...Retourner au dortoir. Vous avez peut être oublié quelque chose', 30, 'defense_point : 1', NULL),
       (33, 'Vous prenez les potions avant de fuir le dortoir',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Direction le Nord !', 13,
        'Direction l''Arène !', 15,
        'Direction le marché !', 14,
        '...Retourner au dortoir. Vous avez peut être oublié quelque chose', 30, 'health_point : 3', NULL),
       (34,
        'Vous vous approchez d''un coffre en face d''un lit occupé. Vous entendez les ronflement de son occupant...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Faire demi-tour. C''était peut-être une mauvaise idée', 12,
        'Ouvrir le coffre...', 24,
        'Prendre le coffre. On l''ouvrira plus tard...', 25,
        'Inspecter le coffre', 26, NULL, NULL),
       (35,
        'Vous approchez d''un aventurier endormis, et le reveillez afin de lui parler. Celui-ci se lève en ralant, enervé par vos actions',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Pardon de vous reveiller... Je suis stagiaire ici et je dois partir en quête mais je n''ai pas d''équipement. Accepteriez vous de m''en preter ?',
        36,
        'Donne moi ton équipement. Maintenant', 37,
        'Je suis envoyé par Isabella. Tu es renvoyé de la guilde et je prend ta place. Tu dois me donner ton équipement',
        37,
        'Hurler de toute vos forces en vous faisant passer pour un démon afin de l''effrayer', 43,
        NULL, NULL),
       (36,
        'L''aventurier rale un peu, remettant sa couverture sur son visage. "Ouais ouais pas de soucis. On commence tous quelque part. Rend le moi une fois victorieux par contre". A l''intérieur de son coffre se trouve une épée, une armure, et des potions',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Formidable ! Direction le Nord maintenant !', 13,
        'Eh bah direction l''arène je suppose maintenant. A moi l''argent ! ', 15,
        'Merci pour votre générosité. Permettez que je l''essaie sur vous maintenant ? ', 37,
        'Merci ! *Planter l''aventurier*', 30, 'attack_point : 2; defense_point : 2; health_point : 2', NULL),
       (37, 'L''aventurier ricanne légèrement. "Mais bien suuur. Casse toi maintenant et laisse moi dormir',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Bon...bah direction le Nord je suppose', 13,
        'Mouais...et bah direction l''arène.', 15,
        'Ne me parle pas comme ça. *Attaquer l''aventurier*', -38,
        'Pff, j''ai même pas besoin de votre aide en fait...', 13, NULL, 3),
       (38,
        'L''aventurier est vaincu (contre toute attente). Mais le bruit de votre bataille a réveillé les autres occupants du dortoir qui ont pris les armes !',
        'Dortoir de la guilde', 'dortoir.jpg',
        'JE NE MOURRAIS PAS SANS ME BATTRE', -98,
        'Zut', 99,
        'C''EST PAS MOI JE VOUS JURE !', 99,
        'Tout ceci n''est qu''un mauvais rêve.... rendormez vous.... s''il vous plait ? ', 99, 'exp : 200', 5),
       (39, 'Il serait pratique de les faire partir. Comment comptez vous faire ?',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Crier au vol et indiquer une direction aléatoire', 40,
        'Crier au meurtre et indiquer une direction aléatoire.', 41,
        '...déclencher un incendie', 42,
        'Hurler de toute vos forces en vous faisant passer pour un démon', 43, NULL, NULL),
       (40,
        'Vous criez au vol, les aventuriers se reveillent en sursaut, indiquant vos directions presque machinalement, les armes en mains. Rapidement, la guilde s''agite, cherchant un coupable, vous laissant seul dans le dortoir, mais pour combien de temps...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Prendre une épee et partir ', 31,
        'Prendre une armure et partir.', 32,
        'Prendre des potions et partir', 33,
        'Dévaliser les dortoirs de tout ce que vous pouvez et partir', 44, NULL, NULL),
       (44,
        'Les aventuriers reviennent et comprennent vos machinations avant que vous ayez eu le temps de vous enfuir avec l''intégralité du butin. Ils prenennt les armes !',
        'Dortoir de la guilde', 'dortoir.jpg',
        'JE NE MOURRAIS PAS SANS ME BATTRE', -98,
        'Zut', 99,
        'C''EST PAS MOI JE VOUS JURE !', 99,
        'Tout ceci n''est qu''un mauvais rêve.... rendormez vous....', 99, NULL, 5),
       (41,
        'Vous hurlez au meurtre, du plus beau jeu d''acteur possible. Les aventuriers se reveillent en sursaut, et partent, les armes en mains, en dehors du couloir, répétant à tout va ce qu''ils ont entendus. Vous êtes rapidement seul dans le dortoir...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Prendre une épee et partir ', 31,
        'Prendre une armure et partir.', 32,
        'Prendre des potions et partir', 33,
        'Dévaliser les dortoirs de tout ce que vous pouvez et partir', 44, NULL, NULL),
       (43,
        'Vous hurlez de manière hystérique que vous êtes un démon nommé Xzéthouguérath, venant profaner leurs ames. Les aventuriers se lèvent alors violement, armes à la main, criant à l''alerte. "MEME PAS DANS TES REVES, DEMON !"',
        'Dortoir de la guilde', 'dortoir.jpg',
        'JE RIGOLAIS !', 45,
        'Ce n''est pas moi ! C''est une voix dans ma tête !', 45,
        'Euh..je..." Seul vos richesses apaiseront ma colère ! Donnez moi tout votre équipement !" ', -98,
        '....On se retrouvera en enfer...*Bruler les dortoirs*', 42, NULL, 5),
       (45, '"Espèce d''idiot ! Dégage de là maintenant !"',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Bon bah direction le nord...', 13,
        'Pardon, je ne recommencerais plus. Je vais aller faire ma quête désormais...', 13,
        '...direction l''arène. J''ai besoin de violence...', 15,
        'J''ai mentis ! A L''ATTAQUE !', -98, NULL, 5),
       (42,
        'Vous prenez rapidement une bougie avant de la renverser sur un lit, qui commence à rapidement s''enflammer. Des cris de paniques commencent à résonner dans les dortoirs, enfumant au passage la pièce. Vous observer avec fascination votre oeuvre, appréciez l''odeur de la chair brulé qui se dégage du lieu, avant de tranquillement partir, les occupants étant trop occupé à contenir l''incendie pour s''occuper de vous...',
        'Dortoir de la guilde', 'dortoir.jpg',
        'Bien. Aux arènes maintenant...', 15,
        'Je crois me souvenir avoir une quête à faire. Cela me fera un parfait alibis !', 13,
        'Allons extorquer quelques personnes au marché', 42,
        'Rester a la guilde. Vous voulez voir le visage de ces personnes traumatisés ', 99, NULL, NULL),
       (98,
        'Par miracle, vous parvenez à vaincre les aventuriers. Véritable criminelle désormais, vous pouvez faire une croix sur votre stage désormais. Mais en avez vous vraiment besoin maintenant ? Vous êtes un puissant combattant, ayant vaincu ceux qui se dressaient sur votre chemin. Le monde tremblera à la seule notion de votre nom. Game over ?',
        'Guilde de Tantrop', 'burned.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (47,
        'Les gobelins s''approchent de vous, levant leurs "armes" dans votre direction. L''un d''entre eux sort un petit bout de papier, posant ses équipements par terre, avant de difficilement le lire :"Bon..bon..jour, mon cieux, dham. Ceux...si haie hein...vole deux vos treux.. car gazon... Veux yénou donne haie veaux byin..Houe, nouvonzatakeron.."',
        'Forêt sombre', 'forest.jpg',
        'J''ai ...pas compris...', 49,
        'Je viens en paix. Discutons. Pourquoi demandez vous mes ressources au lieux de m''attaquer directement? ', 50,
        'Un gobelins qui sait lire ? C''est pas commun ça...', 50,
        'JE NE NEGOCIE PAS AVEC LES MONSTRES !', -48, NULL, 1),
       (49,
        '"A... euh...jeux dis zai : Bon..bon..jour, mon cieux, dham. Ceux...si haie hein...vole deux vos treux.. car gazon... Veux yénou donne haie veaux byin..Houe, nouvonzatakeron.."',
        'Forêt sombre', 'forest.jpg',
        'Toujours pas compris...', 51,
        'Je viens en paix. Discutons. Pourquoi demandez vous mes ressources au lieux de m''attaquer directement? ', 50,
        'Un gobelins qui sait lire ? C''est pas commun ça...', 50,
        'JE NE NEGOCIE PAS AVEC LES MONSTRES !', -48, NULL, 1),
       (51,
        '"Vrai ment ? Bon...euh : Bon..bon..jour, mon cieux, dham. Ceux...si haie hein...vole deux vos treux.. car gazon... Veux yénou donne haie veaux byin..Houe, nouvonzatakeron.."',
        'Forêt sombre', 'forest.jpg',
        'Je te jure que je comprend rien. Articule mieux', 52,
        'Je viens en paix. Discutons. Pourquoi demandez vous mes ressources au lieux de m''attaquer directement? ', 50,
        'Un gobelins qui sait lire ? C''est pas commun ça...', 50,
        'JE NE NEGOCIE PAS AVEC LES MONSTRES !', -48, NULL, 1),
       (52,
        'Vouvou fish et deux moua... Alé :Bon..bon..jour, mon cieux, dham. Ceux...si haie hein...vole deux vos treux.. car gazon... Veux yénou donne haie veaux byin..Houe, nouvonzatakeron.."',
        'Forêt sombre', 'forest.jpg',
        'Nan vraiment, ya pas d''effort de fait..', 53,
        'Je viens en paix. Discutons. Pourquoi demandez vous mes ressources au lieux de m''attaquer directement? ', 50,
        'Un gobelins qui sait lire ? C''est pas commun ça...', 50,
        'JE NE NEGOCIE PAS AVEC LES MONSTRES !', -48, NULL, 1),
       (53, 'Bonba alatak',
        'Forêt sombre', 'forest.jpg',
        'Non non non ! Discutons !', 50,
        'Ose poser la main sur moi et je te fais avaler tes dents', 50,
        'Ah enfin !*Attaquer le gobelin*', -48,
        '*Fuir le gobelin*', 97, NULL, 1),
       (50,
        '"A ? Eux...Dakor. Pardon. Cé notre shef. Ila u liluminassion !" Tous les gobelins derrière agitent les bras en l''air en répétant "ILUMINASSION"." Grasse à lu y, nou deux venu plu un tel y gens. Ilnou a apri a lir et qu''eux tu es sait pa bi un pour rai cup errer dais trucs si non lait a vent tu riez nous tu !"',
        'Forêt sombre', 'forest.jpg',
        'Interessant. Vous pourriez me dire où se trouve votre chef ?', 54,
        'Malin ce gobelin. Je pourrais le rencontrer ? ', 54,
        'Tout ca m''a l''air bien trop dangereux pour un stagiaire comme moi. Je vais m''enfuir...', 97,
        'J''ai tout ce que j''avais besoin de savoir. Mourrez pour moi maintenant ', -48, NULL, 1),
       (48,
        'Dans un dernier souffle, l''un des gobelins murmure "cheeeef..." en rampant dans une direction. Surement celle de son camp...',
        'Forêt sombre', 'forest.jpg',
        'Plus de gobelins à tuer, parfait', 55,
        'Récuperons ce que je peux sur ces cadavres', 56,
        'Je n''ai fait que me défendre. J''espere ne pas devoir recommencer dans le futur', 55,
        'C''était facile. Mais je vais éviter de combattre à nouveau à l''avenir, c''est trop dangereux...', 55,
        'exp : 100', NULL),
       (54, '"Eux...ui ! On vis la ba !" Le gobelin indique une direction',
        'Forêt sombre', 'forest.jpg',
        'Aller en direction que le gobelin a indiqué', 55,
        'Formidable. Maintenant je peux vous tuer !', -48,
        'Venez avec moi, on va rencontrer votre chef !', 55,
        'Cette histoire me dépasse. Je vais rentrer à la guilde...', 97, NULL, 1),
       (55,
        'Vous partez en direction du camp des gobelins. Celui-ci se dresse devant vous, un tas de peau posé sur des os forment des sortes de tentes tribal, et une dizaine de gobelin se baladent dans celui-ci, empilant des objets sur un tas. ',
        'Forêt sombre', 'forest.jpg',
        'Entrer pacifiquement dans le camp', 57,
        'Charger le camp et les attaquer pour profiter de l''effet de surprise', 58,
        'Contourner le camp, les observer, et s''infiltrer', 59,
        'Bruler le camp', 60, NULL, NULL),
       (56,
        'Leur équipement est consituté de dechet plus que d''armes et d''armures. Vous trouvez cependant un bout de papier indiquant le texte que le gobelin devait lire, ainsi qu''une paire de botte meilleure que la votre',
        'Foret sombre', 'forest.jpg',
        'Bon, bah direction le camp. Essayons d''être pacifique cette fois', 57,
        'Je vais charger le camp, les attaquer par surprise', 58,
        'Je vais contourner le camp. Observer et entrer discrètement', 59,
        '....et si je brulais le camp ?', 60, 'speed : 1', NULL),
       (58, 'Vous vous ruez sur le camp, arme à la main, prêt à abattre le moindre adversaire sur votre chemin',
        'Village gobelin', 'goblin_camp.jpg',
        'Viser le chef gobelin, pas de quartier', -64,
        'Trancher tout sur votre passage, personne ne survivra', -64,
        'JE SUIS VOTRE FLEAU, FUYEZ D''ICI TANT QUE VOUS LE POUVEZ ENCORE', 95,
        'Se précipiter sur le chef gobelin. "ON VA PARLER TOI ET MOI. ARRETEZ IMMEDIATEMENT D''ATTAQUER LES CARAVANES"',
        62,
        NULL, 2),
       (59,
        'Vous contournez le camps, et apercevez au loin un gobelin de grande taille, portant une immense couronne de plume. Il semble donner des ordres à d''autres gobelins, debout sur un "trone"',
        'Village gobelin', 'goblin_camp.jpg',
        'Entrer discretement, et assassiner le chef', 64,
        'Bruler le camp', 60,
        'Entrer dans le camp et parler au chef', 57,
        'Charger en criant en direction du chef', 58, NULL, NULL),
       (60,
        'Le feu semble clairement être la meilleure solution en cas de difficulté. Vous allumez une torche, que vous lancez sur une tente. Des cris de terreur, de pleurs et de paniquent résonnent dans la forêt, tandis qu''une odeur de chair brulée emplie vos narines. Le village n''y survivra pas, et vous pouvez retourner triomphant à la guilde, votre victoire (facilement) acquis. *VICTOIRE*',
        'Victoire', 'campburned.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (57,
        'Vous entrez à l''intérieur du camp, les gobelins vous dévisageant alors que vous passer à coté des tentes tribales. Un gobelin s''avance finalement vers vous, plus grand que les autres, il porte une sorte de couronne de plume et un sceptre en bois décoré de quelques joyaux. Ses doigts crochues vous pointent, et sa voix stridente, vous aggresse les oreilles. "Bienvenue dans mon village ! Etranger ! Que puis-je faire pour vous ?"',
        'Village gobelin', 'goblin_camp.jpg',
        'Vous parlez terriblement bien pour un gobelin', 61,
        'Enchanté. Je dois vous parlez de vos attaques sur les villages et les caravanes marchandes', 62,
        'Jolie couronne. A quoi sert-elle ?', 61,
        'Ah c''est vous le chef ? Parfait ! *Attaquer le gobelin*', -64, NULL, 2),
       (64,
        'Votre victoire sur le chef gobelin petrifie de terreur les autres membres de la tribu. Le regard glacé de terreur, ils vous regardent, comme une entité supérieur à craindre',
        'Village gobelin', 'goblin_camp.jpg',
        'Je suis votre chef désormais, vous servirez sous mes ordres', 96,
        'Partez, maintenant. Je ne veux plus jamais vous voir de ma vie', 95,
        'Entretuez vous. Le dernier qui survivra me servira', 94,
        'Je vais purger les monstres que vous êtes *Abbatre les derniers gobelins*', -100, 'exp : 100', 1),
       (61,
        '"Oui ! C''est grâce à mon ILLUMINATION ! " Les autres gobelins derrière agitent les bras en l''air, répétant "ILUMINASSION". "La couronne me l''apporte, me rend intelligent !"',
        'Village gobelin', 'goblin_camp.jpg',
        'Je vois. Je dois vous parler de vos attaques sur les villages et les caravanes cependant...', 62,
        'Je comprend. Et il se passe quoi si je fais ça ? *Prendre la couronne*', 63,
        'Formidable ! Je vais te prendre la couronne du coup. Elle me revient de droit *attaquer le gobelin*', -64,
        'Hmmm, si tu es aussi intelligent, pourquoi ne pas faire autre chose ? ', 65, NULL, 2),
       (62, '"Quoi ? Il y a un problème ? Nous ne blessons que s''ils décident de lutter et nous ne tuons presque pas',
        'Village gobelin', 'goblin_camp.jpg',
        'Justement. Utilisez votre intelligence pour faire autre choses !', 65,
        'Vous blessez des gens, et parfois les tuez. Arretez et trouver un autre moyen de vivre ou vous aurez affaire à moi...',
        66,
        'Je pense que je vais vous abattre. Ca ira plus vite. *Attaquer les gobelins* ', -64,
        'Hmm vous savez quoi ? Vous me plaisez bien. Ca vous dit un aventurier comme garde du corps ?', 93, NULL, 2),
       (63,
        '"NON NE FAITES PAS CA !" Vous arrachez la couronne de la tête du gobelin. Celui-ci tombe à genoux, bouche-bé, la lueur d''intelligence dans ses yeux ayant disparut',
        'Village gobelin', 'goblin_camp.jpg',
        'Mettre la couronne et devenir leur roi', 96,
        'Détruire la couronne. Ils ne sont pas assez intelligent pour survivre seul dans la nature de toute façon...',
        91,
        'Mettre la couronne sur un autre gobelin', 71,
        'Profiter de cet instant de faiblesse pour tuer le chef', 64, NULL, NULL),
       (71,
        'Le nouveau gobelin, à peine la couronne posé sur lui, voit son regard s''emplir d''une lueur d''intelligence. " Je vous remercie, noble aventurier. Grâce à vos actions, j''ai également atteints l''illumination"-"ILUMINASSION"- "Oui oui bref. Je suis à votre service désormais. Que voulez vous ?"',
        'Village gobelin', 'goblin_camp.jpg',
        'JE, suis votre chef désormais, VOUS servirez sous mes ordres', 96,
        'Partez, maintenant. Je ne veux plus jamais vous voir de ma vie', 95,
        'Entretuez vous. Le dernier qui survivra me servira', 94,
        'Je vais purger les monstres que vous êtes *Abbatre les gobelins*', -100, 'exp : 100', NULL),
       (65, '"D''autres trucs ? Comme quoi ?"',
        'Village gobelin', 'goblin_camp.jpg',
        'Pourquoi pas de l''agriculture ? Vous avez déjà pleins d''outils pour !', 66,
        'Hmm ca vous dirait aventurier stagiaire ? Le travail est pas facile, mais en vaut la peine !', 67,
        'Mettez vous à mon service ! Ensemble, nous accomplirons de grande chose !', 66,
        'Au lieu d''attaquer les autres caravanes, protegez les ! Vous verrez du pays, et serez bien payés! ', 66, NULL,
        NULL),
       (66,
        '"Bahahah ! Surement pas ! 2e chance, étranger ! Sinon on vous attaquera et vous devrez nous donner tout ce que vous avez !"',
        'Village gobelin', 'goblin_camp.jpg',
        'Vous savez quoi ? Laissez tomber. Je vais vous abattre ça sera plus simple!', -64,
        'Hmm ca vous dirait aventurier stagiaire ? Le travail est pas facile, mais en vaut la peine !', 67,
        'Mettez vous à mon service ! Ensemble, nous accomplirons de grande chose !', 70,
        'Au lieu d''attaquer les autres caravanes, protegez les ! Vous verrez du pays, et serez bien payés! ', 70, NULL,
        2),
       (67, 'Aventurier ? Ca à l''air marrant. On y fait quoi ?"',
        'Village gobelin', 'goblin_camp.jpg',
        'Des quêtes, des missions, comme j''en fait actuellement.', 70,
        'On aide des gens, parfois on les tues, et on est payé pour ça !', 72,
        'Je sais pas, je viens de débuter. Mais tu es payé ! Un brin d''inconnu c''est excellent dans la vie non ?', 72,
        'Ca par exemple : *Attaquer le gobelin*', -64, NULL, 2),
       (72,
        'le gobelin rie aux éclats. Ses dents acéré comme des poignards jaunes brillent sous la lumière du soleil estival. "J''adore ! Vous savez quoi, c''est d''accord. Ca m''a l''air marrant !"',
        'Village gobelin', 'goblin_camp.jpg',
        'Formidable ! Nous ferons de grandes choses ensemble', 92,
        'On verra si vous serez à la hauteur', 92,
        'Je suis votre supérieur maintenant ca veut dire. Vous me devez le respect', 92,
        'J''ai changé d''avis, vous êtes trop dangereux *attaquer le gobelin*', -64, NULL, 2),
       (70, '"Mouais...vous m''ennuyez. Je vais vous depouiller ca sera plus simple"',
        'Village gobelin', 'goblin_camp.jpg',
        'Tant pis pour vous...', -64,
        'Ca aurait put mieux se passer pour vous, tant pis', -64,
        'Vous perirez sous ma lame, monstres !', -64,
        'Pitiez écoutez moi !', -64, NULL, 2),
       (91,
        'Vous détruisez la couronne et laissez les gobelins à la merci de mère nature. Ils s''entretueront surement prochainement pour leur place de chef, et les loups acheveront les derniers avant la nuit tombé. Vous rentrez alors victorieux à la guilde, votre CDI en poche. *VICTOIRE*',
        'Victoire', 'goblin_camp.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (92,
        'Vous retournez triomphant à la guilde, les gobelins avec vous. Votre quête est accomplis, bien que cette victoire est pour le moins... surprenante. Mais une victoire est une victoire, et votre CDI est en poche ! **VICTOIRE**',
        'Victoire !', 'tantrop.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (93,
        'Le gobelin en chef accepte immédiatement, saute de joie, et vous offre une place à ses cotés, un trone rien que pour vous à ses cotés. Grâce à vous et à son intelligence, votre troupe se développera vite, et efficacement, ainsi que votre réputation. Il ne faudra pas attendre longtemps pour voir d''autres aventurier venir à votre rencontre...',
        'Victoire ? ', 'goblin_camp.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (94,
        'Les gobelins hurlent de peur et de rage, attrapant ce qu''ils peuvent pour commencer à s''entretuer. La symphonie des os se brisant sous les coups desesperés des gobelins est une mélodie, où les chants sont les cris de rage, de terreur, et les pleurs des pauvres monstres s''entretuant pour votre plaisir. En quelques seconde, il ne reste qu''un unique gobelin, encore vivant, en piteux état, rampant dans votre direction',
        'Village gobelin', 'goblin_camp.jpg',
        'Achever le gobelin', 100,
        'C''est bien. Tu t''appellerais Nigolb et me servira éternellement en tant que mon escl...stagiaire personnel.',
        101,
        'Pars. Loin. Tout de suite', 101,
        'Jeter votre arme au gobelin et l''affronter à la loyal', -100, NULL, 1),
       (101,
        'Le camp de gobelin n''est plus, et vous retournez enfin à la guilde, victorieux, votre CDI en poche. *VICTOIRE*',
        'VICTOIRE', 'tantrop.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (100,
        '"NON ! JE VOUS EN PRIE" sera les dernière paroles du dernier gobelin avant que sa nuque ne rencontre votre talon, laissant entendre un "crac" satisfaisant. Vous rentrez enfin à la guilde, victorieux, et obtenez votre CDI. *VICTOIRE*',
        'VICTOIRE', 'goblin_camp.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (95,
        'Les gobelins n''attendent pas un mot de plus de votre part et s''enfuient à toute jambe le plus loins possible de vous. Vous rentrez triomhant à la guilde, votre victoire accomplis, et obtenez votre CDI ! *Victoire*',
        'VICTOIRE', 'tantrop.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (96,
        'Les gobelins se ruent à vos pieds, et vous remercient de les épargner. Ils vous fabriquent immédiatement un trone à votre mesure, et vous serez connue au sein de la guilde comme le nouveau roi des gobelins. *VICTOIRE* !',
        'VICTOIRE !', 'goblin_camp.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (97,
        'Vous avez fuis votre quête, et faites la honte de la guilde. Votre stage à été annulé,et n''aurez jamais votre CDI...Game Over',
        'Tantrop', 'tantrop.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (99,
        'Vous vous faites arreter par la guilde, signant la fin de votre stage ( et de votre vie accessoirement...). Game OVER',
        'Guilde de Tantrop', 'tantrop.jpg',
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999,
        'Rejouer', 999, NULL, 6),
       (999,
        'Bravo. Vous avez battu un adversaire supposé invincible. Tricheur ou farmeur de l''arène, vous gagnez cette image de chaton en récompense',
        'Un chaton', 'secret_ending.png',
        'il n''y a plus d''interet à jouer maintenant', 999,
        'Vous devriez relancer le jeu', 999,
        'Vraiement', 999,
        'Il est beau ce chaton hein ?', 999, NULL, 6);