INSERT INTO hero (name, image, level, health_point, attack_point, defense_point, magic_point, exp, speed)
VALUES ('Hero1', NULL, 1, 8, 5, 2, 2, 0, 1);

INSERT INTO monsters (name, image, hp_min, hp_max, atk_min, atk_max, def_min, def_max, mag_min, mag_max, xp_drop,
                      speed_min, speed_max)
VALUES ('Monster1', NULL, 10, 30, 4, 7, 1, 3, 1, 2, 205, 2, 5),
       ('Monster2', NULL, 20, 40, 2, 3, 2, 4, 2, 3, 102, 1, 3),
       ('Monster3', NULL, 1, 2, 2, 4, 3, 5, 1, 2, 45, 1, 8);

INSERT INTO story (descriptionID, text_description, localisation, image, option1, redirection1, option2, redirection2,
                   option3, redirection3, option4, redirection4, effects, monsterID)
VALUES (1,
        'Bonjour, et bienvenue dans Javaquest. Vous vous appretez à vivre une aventure incroyable, où vos décisions seront importantes, et vos ennemis implacables. ' ||
        'Voyons un peu comment vous souhaitez jouez votre héros. Fasse à un adversaire, comment décidez vous de combattre >? ',
        '???', NULL, 'Prudemment. Je dois attendre le moment opportun pour frapper (+ 2 pv)', 2,
        'Taper. Fort. ( +1 attaque)', 3,
        'J utiliserais ma puissante armure pour échanger les attaques avec mon adversaire. Mais en ayant toujours un avantage ( +1 défense)',
        4,
        'Rapide, efficace, frappant avant que mon adversaire ne puisse réagir (+2 vitesse)', 5, NULL, NULL),
       (2,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', NULL, 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'health_point:2', NULL),
       (3,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '??', NULL, 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'attack_point:1', NULL),
       (4,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', NULL, 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'defense_point:1', NULL),
       (5,
        'Je vois. Mais vous ne devriez pas oubliez que la violence devrait être utilisé en dernier recours. Une rencontre pacifique sera bien plus rentable',
        '???', NULL, 'Ouais....On verra', 6, 'Je met les pieds ou je veux, et souvent dans les visages', 6,
        'Evidemment. Je me battrais en ultime recours', 7,
        'Je ne possède aucun ennemi. Je ne me battrais que pour me proteger', 7, 'speed :2', NULL),
       (6,
        'Espérons que tes pulsions de violences te permettront tout de même de survivre. Es tu prêt à partir en aventure ?',
        '???', NULL, 'Je suppose ?', 8, 'ABSOLUMENT !', 8, 'Pas vraiment le choix en fait...', 8, 'Euh.... non ?', 8,
        NULL, NULL),
       (7, 'Un bel état d esprit ! Es tu prêt à partir en aventure ?', '???', NULL, 'Je suppose ?', 8, 'ABSOLUMENT !',
        8, 'Pas vraiment le choix en fait...', 8, 'Euh.... non ?', 8, NULL, NULL),
       (8,
        'Vous êtes, un aventurier de la guilde de Tantrop. Que ce soit à la recherche de gloire, de fortune, d''aventure ou de quelques relations hauts placés, vous avez réussis le difficile test de recrutement et êtes désormais un stagiaire aventurier, à la recherche d''un Contrat de Decouverte et d''Initiation, premier pas dans le vrai monde d''un aventurier. Assis au milieu de la taverne, vous attendez l''arrivé dIsabella, responsable de la guilde, qui va vous proposer une quete à réaliser... ' ||
        'Une naine aux cheveux roux, de longues couettes attaché par 2 gros anneaux de métal, les cheveux bouclés se présente devant vous. Son visage rond décorés d yeux semblables à 2 émeraudes et des lèvres fines, vous sourit tendrement,avant de transformer son visage en une grimace de dégout et vulgaire.' ||
        '"Bon sang, on accepte vraiment n''importe qui ici de nos jours. T''es censé être quoi en fait ?',
        'Taverne de Tantrop', NULL, 'Isabella, je suppose ?', 9,
        'Je te permet pas de me parler comme ça. Tu cherches les problèmes ?', 10,
        'Un stagiaire aventurier ne souhaitant que faire ses preuves !', 11,
        'Je ne sais pas vraiment...Mon école m''impose un stage et j''ai juste été pris(e) ici...', 11, NULL, NULL),
       (9,
        '"Elle même. Cheffe en second de la guilde. Tu dois être le nouveau stagiaire ici je suppose ? Je vais te filer une petite quête, facile et rapide. Enfin, si t es pas trop stupide. Heh... ',
        'Taverne de Tantrop', NULL, 'Stupide moi ? Je suis peut-être idiot mais pas non plus stupide hein..', 11,
        'Je suis stagiaire ici oui. Merci de m offrir une chance', 11,
        'Tu oses m insulter ? Je vais t apprendre le respect moi... *Frapper Isabella*', 10,
        'Jai hate de chatier mes ennemis...', 11, NULL, NULL),
       (10,
        'Avant d avoir put réagir, une baffe capable de déboiter une machoire se pose "délicatement" sur votre joue. Un son lourd et sourd résonnant dans votre crane vous fait perdre la vue quelques secondes. Vous ne parvenez qu''à entendre que le son de votre sang montant par pulsion dans votre cerveau, votre corps luttant pour reprendre conscience. Votre vue revient petit à petit, et vous appercevez Isabella, tournant son poignet, le regard fier et hautain. Vous avez perdu 2 pv.' ||
        '" Tu disais le nouveau ?', 'Taverne de Tantrop', NULL, 'Pardon', 11, 'C''était...innatendu... ', 11,
        'Je rigolais, je te jure...;', 11,
        'Tu verras quand je serais plus fort. J''aurais ma revanche...', 11, 'health_point : -2', NULL),
       (11,
        '" Formidable ! Voici ta quête : Un groupe de gobelin au nord de la ville ont commencé à piller les caravanes marchandes et les villages alentours. Cependant, ils ne semblent pas être particulièrement violent. Ils pillent, blessent parfois, mais n''ont tué que ceux qui l''ont attaqué. Un stratagème inhabituel pour des gobelins. Va sur place, comprend ce qu''il se passe, et règle le problème. Des questions ? *Son poing se lève*  ',
        'Taverne de Tantrop', NULL, 'Non...', 12, 'Non...', 12, 'Non...', 12,
        'En fait, oui...', 12, NULL, NULL),
       (12,
        '"Très bien ! Bon courage alors" Isabella tourne les talons, vous laissant seul à votre table. Que souhaitez vous faire ?',
        'Taverne de Tantrop', NULL, 'Eh bah direction le nord alors...', 13,
        'Il me faudrait de l''argent. Et de l''équipement. Direction le marché avant tout ', 14,
        'Il me faudrait de l argent, et vite. Direction l''arène !', 15,
        'Personne ne m''en voudra si.... "j''emprunte" un peu d''équipement à la guilde n''est ce pas ? Direction les casiers privés des autres aventuriers...',
        16, NULL, NULL),
       (13,
        ' Une odeur fétide agresse vos narines alors que vous arrivez aux écuries du nord de la ville. Devant vous, des chevaux sellés attachés semblent attendre leur cavaliers. A coté, un groupe de marchand préparent leur cargaisons dans un chariot tiré par deux mules. Enfin, la porte permettant de sortir de la ville est grande ouverte devant vous  ',
        'Ecuries de Tantrop', NULL, 'Ce cheval sera à moi...', 17, 'Parlons au propriétaire. Jai besoin d un cheval',
        18, 'Bah ! J irais à pied', 19,
        'Allons parler aux marchands.Isabella a bien dit que les gobelins les attaquaient non ?', 20, NULL, NULL),
       (14,
        'Les étals colorés débordent d''une myriade de marchandises exotiques venues des confins du monde connu. Les odeurs enivrantes d''épices rares et de potions magiques flottent dans l''air, tandis que le brouhaha des négociations et les rires des marchands créent une symphonie animée par des musiciens créant une ambiance envoutante. Des tentes ornées de drapés chatoyants s''étirent sous le ciel, abritant des trésors éblouissants, des artefacts mystiques, des bijoux incrustés de gemmes aux propriétés mystiques, des étoffes aux couleurs éclatantes de tissus enchantés, des herbes rares aux vertus curatives et des marchandises inconnues...Des forgerons martèlent le métal avec une habileté ancestrale, créant des armes ornées de runes magiques' ||
        '.', 'Le marché', NULL, 'Magnifique. Essayons d''acheter de l''équipement !', 21,
        'J''ai pas d''argent. Tant pis, voyons ce que je peux voler...', 22,
        'Je suis un as de la négociation. J''arriverais bien à choper 2-3 trucs gratos', 21,
        'Pas d''argent.... Retournons à la guilde', 12, NULL, NULL),
       (15,
        'Les bruits d''armes d''acier se fracassant les unes contre les autres resonnent dans l''accueil de l''arène. Les cris de guerres, de douleur, et de victoire semblable à des échos terrifiant dans la salle. Un homme s''approche de vous, grand, musclé, les bras croisés. "Salut. Tu veux quoi ici ? "',
        'Arène de Tantrop', NULL,
        'Euh... rien je me suis perdu...', 0,
        'GLOIRE ET FORTUNE', 0,
        'Rien je cherchais les toilettes...', 0,
        'Vous parlez à un (stagiaire) aventurier, un peu de respect ! Je viens m''échauffer avant de partir en quête !', 0,
        NULL, NULL),
       (16,'Vous entrez au niveau des dortoirs de la guilde, une succession de lit superposé dans une grande salle, avec un coffre au pied de chacun d''entre eux. Certains aventuriers dorment encore...',
        'Dortoir de la guilde', NULL,
        '*S''approcher du coffre d''un lit où personne ne dort...*', 23,
        '*S''approcher du coffre d''un lit où un aventurier dort...*', 34,
        '*Reveiller un aventurier pour lui demander de l''aide ', 35,
        '*Réflechir à une distraction pour faire sortir les gens de la salle*', 0, NULL, NULL),
       (17,'histoire',
        'Le marché', NULL,
        '1', 21,
        '2', 22,
        '3', 21,
        '4', 12, NULL, NULL),
       (18,'histoire',
        'Le marché', NULL,
        '1', 21,
        '2', 22,
        '3', 21,
        '4', 12, NULL, NULL),
       (19,'histoire',
        'Le marché', NULL,
        '1', 21,
        '2', 22,
        '3', 21,
        '4', 12, NULL, NULL),
       (20,'histoire',
        'Le marché', NULL,
        '1', 21,
        '2', 22,
        '3', 21,
        '4', 12, NULL, NULL),
       (21,'histoire',
        'Le marché', NULL,
        '1', 21,
        '2', 22,
        '3', 21,
        '4', 12, NULL, NULL),
       (22,'histoire',
        'Le marché', NULL,
        '1', 21,
        '2', 22,
        '3', 21,
        '4', 12, NULL, NULL),
       (23,'Vous vous approchez d''un coffre en face d''un lit vide...',
        'Dortoir de la guilde', NULL,
        'Faire demi-tour. C''était peut-être une mauvaise idée', 12,
        'Ouvrir le coffre...', 24,
        'Prendre le coffre. On l''ouvrira plus tard...', 25,
        'Inspecter le coffre', 26, NULL, NULL),
       (24,'Le coffre s''ouvre sans opposer de résistance. Une petite dague est trouvable à l''intérieur !',
        'Dortoir de la guilde ', NULL,
        'Prendre la dague ! (+1 attaque)', 27,
        'Laisser la dague. Le vol c''est mal...', 16,
        'Prendre la dague et planter les aventurier. On sera plus tranquille sans eux dans le dortoir...', 28,
        'Crier au vol et indiquer une direction pour faire partir les aventuriers',40, NULL, NULL),
       (25,'Vous essayer de tirer le coffre, mais celui-ci est trop lourd...',
        'Dortoir de la guilde', NULL,
        'Prendre une inspiration et reessayer', 25,
        'Tant pis, ouvrir le coffre...', 24,
        'Inspecter le coffre, peut être que quelque chose bloque le coffre...', 26,
        'Laisser tomber. C''est trop dangereux de voler la guilde...', 12, NULL, NULL),
       (26,'Le coffre est en bois avec des gondons de métal lourd pour le soutenir. Pas de cadenas visible. Après courte inspection, il semble cloué dans le sol...',
        'Dortoir de la guilde', NULL,
        'Ouvrir le coffre', 24,
        'Laissez tomber et aller ailleur...', 12,
        'Laisser tomber et demander de l''aide à un aventurier plutôt que de les voler', 0,
        'Insister. Le coffre. Cèdera.', 25, NULL, NULL),
       (27,'Vous prenez la dague !',
        'Dortoir de la guilde', NULL,
        'Planter un aventurier pour essayer la dague', 28,
        'Planter les aventuriers pour les dépouiller de leur richesse. Après tout, morts, elles vous seront plus utiles', 28,
        'Partir avant de vous faire reperer, et partir au Nord', 13,
        'Avec ça, aucune chance de perdre à l''Arène. Direction celle-ci !', 15,
        'attack_point : 1', NULL),
       (28,'Votre dague en main, vous cedez à vos pulsions de violence et plantez un aventurier. La lame s''enfonce dans sa gorge, le sang pulsant dans un rythme régulier en dehors de son corps. Les yeux de votre victime s''écarquillent de terreur, ses yeux rouges, au bord des larmes, tandis qu''il commence à convulser de douleur, un son de rale tandis qu''il s''étouffe dans son propre sang, avant d''être un cadavre inerte, encore chaud, devant vous',
        'Dortoir de la guilde', NULL,
        'Piller le coffre et le cadavre', 29,
        '......En planter un autre....', 30,
        'Partir d''ici rapidement, l''odeur va rapidement attirer du monde. Direction le Nord', 13,
        'Crier au meurtre en indiquant une direction', 41, 'attack_point : 1', NULL),
       (29,'Les gemissements de votre victime ont commencé à reveiller quelques personnes. Des mouvements de draps, des grognements, suivi d''un leger "Que se passe-t-il ?" resonnent dans le dortoir...',
        'Dortoir de la guilde', NULL,
        'Il a une épée sur lui. La prendre et partir en courant !', 31,
        'Il a une armure sur lui. La prendre et partir en courant !', 32,
        'Des potions ! Les prendre et partir en courant !', 33,
        'PRENDRE TOUT', 30, NULL, NULL),
       (30,'Le bruit incessant que vous avez provoqué à reveillé les occupants du dortoir. Les aventuriers se lèvent, et observent votre crime, dégainant leurs armes et chargeant vers vous ! ',
        'Dortoir de la guilde', NULL,
        'JE NE MOURRAIS PAS SANS ME BATTRE', -98,
        'Zut', 99,
        'C''EST PAS MOI JE VOUS JURE !', 99,
        'Tout ceci n''est qu''un mauvais rêve.... rendormez vous....', 99, NULL, NULL),
       (31,'Vous prenez une épée avant de fuir le dortoir',
        'Dortoir de la guilde', NULL,
        'Direction le Nord', 13,
        'Direction l''Arène !', 15,
        'Direction le marché' , 14,
        '...Retourner au dortoir. Vous avez peut être oublié quelque chose', 30, 'attack_point : 1', NULL),
       (32,'Vous prenez une armure avant de fuir le dortoir',
        'Dortoir de la guilde', NULL,
        'Direction le Nord !', 13,
        'Direction l''Arène !', 15,
        'Direction le marché !', 14,
        '...Retourner au dortoir. Vous avez peut être oublié quelque chose', 30, 'defense_point : 1', NULL),
       (33,'Vous prenez les potions avant de fuir le dortoir',
        'Dortoir de la guilde', NULL,
        'Direction le Nord !', 13,
        'Direction l''Arène !', 15,
        'Direction le marché !', 14,
        '...Retourner au dortoir. Vous avez peut être oublié quelque chose', 30, 'health_point : 3', NULL),
       (34,'Vous vous approchez d''un coffre en face d''un lit occupé. Vous entendez les ronflement de son occupant...',
        'Dortoir de la guilde', NULL,
        'Faire demi-tour. C''était peut-être une mauvaise idée', 12,
        'Ouvrir le coffre...', 24,
        'Prendre le coffre. On l''ouvrira plus tard...', 25,
        'Inspecter le coffre', 26, NULL, NULL),
       (35,'Vous approchez d''un aventurier endormis, et le reveillez afin de lui parler. Celui-ci se lève en ralant, enervé par vos actions',
        'Dortoir de la guilde', NULL,
        'Pardon de vous reveiller... Je suis stagiaire ici et je dois partir en quête mais je n''ai pas d''équipement. Accepteriez vous de m''en preter ?', 36,
        'Donne moi ton équipement. Maintenant', 37,
        'Je suis envoyé par Isabella. Tu es renvoyé de la guilde et je prend ta place. Tu dois me donner ton équipement', 37,
        'Hurler de toute vos forces en vous faisant passer pour un démon afin de l''effrayer', 43,
        NULL, NULL),
       (36,'L''aventurier rale un peu, remettant sa couverture sur son visage. "Ouais ouais pas de soucis. On commence tous quelque part. Rend le moi une fois victorieux par contre". A l''intérieur de son coffre se trouve une épée, une armure, et des potions',
        'Dortoir de la guilde', NULL,
        'Formidable ! Direction le Nord maintenant !', 13,
        'Eh bah direction l''arène je suppose maintenant. A moi l''argent ! ', 15,
        'Merci pour votre générosité. Permettez que je l''essaie sur vous maintenant ? ', 37,
        'Merci ! *Planter l''aventurier*', 30, 'attack_point : 2; defense_point : 2; health_point : 2', NULL),
       (37,'L''aventurier ricanne légèrement. "Mais bien suuur. Casse toi maintenant et laisse moi dormir',
        'Dortoir de la guilde', NULL,
        'Bon...bah direction le Nord je suppose', 13,
        'Mouais...et bah direction l''arène.', 15,
        'Ne me parle pas comme ça. *Attaquer l''aventurier*', -38 ,
        'Pff, j''ai même pas besoin de votre aide en fait...', 13, NULL, NULL),
       (38,'L''aventurier est vaincu (contre toute attente). Mais le bruit de votre bataille a réveillé les autres occupants du dortoir qui ont pris les armes !',
        'Dortoir de la guilde', NULL,
        'JE NE MOURRAIS PAS SANS ME BATTRE', -98,
        'Zut', 99,
        'C''EST PAS MOI JE VOUS JURE !', 99,
        'Tout ceci n''est qu''un mauvais rêve.... rendormez vous.... s''il vous plait ? ', 99, 'exp : 200', NULL),
       (39,'Il serait pratique de les faire partir. Comment comptez vous faire ?',
        'Dortoir de la guilde', NULL,
        'Crier au vol et indiquer une direction aléatoire', 40,
        'Crier au meurtre et indiquer une direction aléatoire.', 41,
        '...déclencher un incendie', 42 ,
        'Hurler de toute vos forces en vous faisant passer pour un démon', 43, NULL, NULL),
       (40,'Vous criez au vol, les aventuriers se reveillent en sursaut, indiquant vos directions presque machinalement, les armes en mains. Rapidement, la guilde s''agite, cherchant un coupable, vous laissant seul dans le dortoir, mais pour combien de temps...',
        'Dortoir de la guilde', NULL,
        'Prendre une épee et partir ', 31,
        'Prendre une armure et partir.', 32,
        'Prendre des potions et partir', 33 ,
        'Dévaliser les dortoirs de tout ce que vous pouvez et partir', 44, NULL, NULL),
       (44,'Les aventuriers reviennent et comprennent vos machinations avant que vous ayez eu le temps de vous enfuir avec l''intégralité du butin. Ils prenennt les armes !',
        'Dortoir de la guilde', NULL,
        'JE NE MOURRAIS PAS SANS ME BATTRE', -98,
        'Zut', 99,
        'C''EST PAS MOI JE VOUS JURE !', 99,
        'Tout ceci n''est qu''un mauvais rêve.... rendormez vous....', 99, NULL, NULL),
       (41,'Vous hurlez au meurtre, du plus beau jeu d''acteur possible. Les aventuriers se reveillent en sursaut, et partent, les armes en mains, en dehors du couloir, répétant à tout va ce qu''ils ont entendus. Vous êtes rapidement seul dans le dortoir...',
        'Dortoir de la guilde', NULL,
        'Prendre une épee et partir ', 31,
        'Prendre une armure et partir.', 32,
        'Prendre des potions et partir', 33 ,
        'Dévaliser les dortoirs de tout ce que vous pouvez et partir', 44, NULL, NULL),
       (43,'Vous hurlez de manière hystérique que vous êtes un démon nommé Xzéthouguérath, venant profaner leurs ames. Les aventuriers se lèvent alors violement, armes à la main, criant à l''alerte. "MEME PAS DANS TES REVES, DEMON !"',
        'Dortoir de la guilde', NULL,
        'JE RIGOLAIS !', 45,
        'Ce n''est pas moi ! C''est une voix dans ma tête !', 45,
        'Euh..je..." Seul vos richesses apaiseront ma colère ! Donnez moi tout votre équipement !" ', -38 ,
        '....On se retrouvera en enfer...*Bruler les dortoirs*', 42, NULL, NULL),
       (45,'"Espèce d''idiot ! Dégage de là maintenant !"',
        'Dortoir de la guilde', NULL,
        'Bon bah direction le nord...', 13,
        'Pardon, je ne recommencerais plus. Je vais aller faire ma quête désormais...', 13,
        '...direction l''arène. J''ai besoin de violence...', 15 ,
        'J''ai mentis ! A L''ATTAQUE !', -38, NULL, NULL),
       (42,'Vous prenez rapidement une bougie avant de la renverser sur un lit, qui commence à rapidement s''enflammer. Des cris de paniques commencent à résonner dans les dortoirs, enfumant au passage la pièce. Vous observer avec fascination votre oeuvre, appréciez l''odeur de la chair brulé qui se dégage du lieu, avant de tranquillement partir, les occupants étant trop occupé à contenir l''incendie pour s''occuper de vous...',
        'Dortoir de la guilde', NULL,
        'Bien. Aux arènes maintenant...', 15,
        'Je crois me souvenir avoir une quête à faire. Cela me fera un parfait alibis !', 13,
        'Allons extorquer quelques personnes au marché', 42 ,
        'Rester a la guilde. Vous voulez voir le visage de ces personnes traumatisés ', 99, NULL, NULL),
       (99,'Vous vous faites arreter par la guilde, signant la fin de votre stage ( et de votre vie accessoirement...). Game OVER',
        'Le marché', NULL,
        'Rejouer', 1,
        'Rejouer', 1,
        'Rejouer', 1,
        'Rejouer', 1, NULL, NULL),;